### ISSUE TITLE
Add synced zoom to overlay slide mode

### ISSUE THREAD

**Issue by bigConifer** [VincentEngel/VES-Image-Compare#25] opened 2022-11-26 19:40 UTC
I think there are 3 ways to implement synced zoom in overlay slide mode:

1. keep slider position when zooming, reset zoom when sliding
2. keep slider position when zooming, slide always over the whole image width (left and/or right end of the slider refers to parts of the image out of the screen boundaries => no visual feedback when sliding there)
3. update the slider when zooming or moving => slider always refers to the current displayed image section.

The first one should be the easiest to implement and enough for the moment.

**Comment by bigConifer** [comment] 2022-11-26 19:56
Instead of adding a hidable sync button in this mode too, it might be worth to discuss a little bit more if distributed sync buttons are still required. See https://github.com/VincentEngel/VES-Image-Compare/issues/10#issuecomment-1326926418.

If there was only the new synced zoom botton on home, the new extensions button would only enable/disable captions, which would be more intuitive. And the puzzle icon could be replaced e.g. with the better looking [subtitles icon](https://fonts.google.com/icons?icon.platform=android&icon.query=subtitles) (corssed version of it is easy to create)...

**Comment by VincentEngel** [comment] 2022-11-27 11:12
The problem is that I am using https://github.com/davemorrissey/subsampling-scale-image-view for the Zoom etc. features. However I don't know how to get zoomed in image.

I might have to look for a new library anyway, because the current one is no longer mainted and doesnt support sdk 33. But this is not a priority right now.

**Comment by VincentEngel** [comment] 2022-11-27 11:15
Maybe https://github.com/MikeOrtiz/TouchImageView is a good alternative. It has a `RectF getZoomedRect();` method.

**Comment by bigConifer** [comment] 2022-11-27 15:19
Yes, I agree, adding `android.permission.INTERNET` would not be a good alternative.

However, do you need to get the zoomed image for variant 1? It shouldn't differ so much from zoom in the other modes 🤔

**Comment by VincentEngel** [comment] 2022-11-27 16:15
Ah you are right, I misunderstood your first suggestion. I will look into it 👍

**Comment by bigConifer** [comment] 2022-11-27 16:52
Thanks, corrected it...

**Comment by VincentEngel** [comment] 2022-11-28 07:12
Thanks for the suggestion 👍 I added the synced zoom feature and it will be part of the next release https://github.com/VincentEngel/VES-Image-Compare/commit/6df8a4b637ec5c0b0e7ef0af61c793fec05a7852

I did not add an enable/disable synced zoom button for now and therefore kept the main activity button for enable/disable extensions. I did not forget about it and I know you were correct the last time 😉 So maybe I will change it in the future

**Closed by VincentEngel** 2022-11-28 07:12 UTC
Labels: enhancement
